import type { RemediationPlan, RemediationTask } from '../types.js';

export function generateRemediationReport(plan: RemediationPlan, projectName?: string): string {
  const lines: string[] = [];
  const gap = plan.targetScore - plan.currentScore;
  const now = new Date().toISOString().split('T')[0];

  // --- Header ---
  lines.push(`# LUCID Remediation Plan — ${projectName || 'Audit Results'}`);
  lines.push('');
  lines.push(`*Generated: ${now}*`);
  lines.push(`*Iteration: ${plan.iteration}*`);
  lines.push(`*Codebase: ${plan.codebasePath}*`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // --- Score Summary ---
  lines.push('## Compliance Gap');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Current score | **${plan.currentScore.toFixed(1)}%** |`);
  lines.push(`| Target score | ${plan.targetScore}% |`);
  lines.push(`| Gap | ${gap.toFixed(1)} points |`);
  lines.push(`| Total fix tasks | ${plan.totalTasks} |`);
  lines.push('');

  // --- Summary Tables ---
  lines.push('## Task Summary');
  lines.push('');
  lines.push('**By verdict:**');
  lines.push('');
  lines.push(`| Verdict | Tasks |`);
  lines.push(`|---------|-------|`);
  lines.push(`| FAIL | ${plan.tasksByVerdict.fail} |`);
  lines.push(`| PARTIAL | ${plan.tasksByVerdict.partial} |`);
  lines.push('');

  lines.push('**By severity:**');
  lines.push('');
  lines.push(`| Severity | Tasks |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Critical | ${plan.tasksBySeverity.critical} |`);
  lines.push(`| High | ${plan.tasksBySeverity.high} |`);
  lines.push(`| Medium | ${plan.tasksBySeverity.medium} |`);
  lines.push(`| Low | ${plan.tasksBySeverity.low} |`);
  lines.push('');

  // Effort distribution
  const effortCounts = { trivial: 0, small: 0, medium: 0, large: 0 };
  for (const t of plan.tasks) {
    effortCounts[t.estimatedEffort]++;
  }

  lines.push('**By effort:**');
  lines.push('');
  lines.push(`| Effort | Tasks |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Trivial | ${effortCounts.trivial} |`);
  lines.push(`| Small | ${effortCounts.small} |`);
  lines.push(`| Medium | ${effortCounts.medium} |`);
  lines.push(`| Large | ${effortCounts.large} |`);
  lines.push('');

  // --- Priority sections ---
  const severityGroups: Array<{ label: string; severity: string }> = [
    { label: 'Critical Priority', severity: 'critical' },
    { label: 'High Priority', severity: 'high' },
    { label: 'Medium Priority', severity: 'medium' },
    { label: 'Low Priority', severity: 'low' },
  ];

  for (const group of severityGroups) {
    const groupTasks = plan.tasks.filter((t) => t.severity === group.severity);
    if (groupTasks.length === 0) continue;

    lines.push('---');
    lines.push('');
    lines.push(`## ${group.label} (${groupTasks.length} tasks)`);
    lines.push('');

    for (const task of groupTasks) {
      renderTask(lines, task);
    }
  }

  // --- Quick Wins ---
  const quickWins = plan.tasks
    .filter((t) => t.verdict === 'PARTIAL')
    .sort((a, b) => {
      const effortOrder = { trivial: 0, small: 1, medium: 2, large: 3 };
      return effortOrder[a.estimatedEffort] - effortOrder[b.estimatedEffort];
    });

  if (quickWins.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push(`## Quick Wins (${quickWins.length} partial implementations)`);
    lines.push('');
    lines.push('These claims are partially implemented — completing them yields the most score improvement per effort.');
    lines.push('');

    for (const task of quickWins) {
      lines.push(`- [ ] **${task.id}** [${task.estimatedEffort}] ${task.title} → \`${task.targetFiles.join('`, `')}\``);
    }
    lines.push('');
  }

  // --- Footer ---
  lines.push('---');
  lines.push('');
  lines.push('## Next Steps');
  lines.push('');
  lines.push('1. Fix the tasks above, starting with Critical Priority');
  lines.push('2. Re-verify: `lucid verify`');
  lines.push('3. Re-report: `lucid report`');
  lines.push(`4. Repeat until compliance score >= ${plan.targetScore}%`);
  lines.push('');
  lines.push('```');
  lines.push('verify → report → remediate → [fix code] → verify → report → ...');
  lines.push('```');
  lines.push('');
  lines.push(`*Report generated by LUCID v0.1.0 — Leveraging Unverified Claims Into Deliverables*`);
  lines.push(`*https://franklabs.io/lucid*`);
  lines.push('');

  return lines.join('\n');
}

function renderTask(lines: string[], task: RemediationTask): void {
  const verdictBadge = task.verdict === 'FAIL' ? '[FAIL]' : '[PARTIAL]';

  lines.push(`### ${task.id}: ${task.title}`);
  lines.push('');
  lines.push(`${verdictBadge} **${task.severity}** | Action: \`${task.action}\` | Effort: \`${task.estimatedEffort}\` | Claim: \`${task.claimId}\``);
  lines.push('');
  lines.push(task.description);
  lines.push('');

  if (task.targetFiles.length > 0) {
    lines.push('**Target files:**');
    for (const f of task.targetFiles) {
      lines.push(`- \`${f}\``);
    }
    lines.push('');
  }

  if (task.codeGuidance) {
    lines.push('**Code guidance:**');
    lines.push('');
    lines.push(`> ${task.codeGuidance.split('\n').join('\n> ')}`);
    lines.push('');
  }
}
